version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: microsoft/aspnetcore-build:2

    working_directory: ~/repo

    steps:
      - checkout

      - run: cd SmarterBalanced.SpanishEnglishDemarcation
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run: apt-get update
      - run: apt-get install nodejs -y
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run lint