version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2

    working_directory: ~/repo

    steps:
      - checkout

      - run: cd SmarterBalanced.SpanishEnglishDemarcation

      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run: apt-get update
      - run: apt-get install nodejs -y
      - run: npm ci

      - run: dotnet build