version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Run MSBuild
          command: dotnet build

  push_image:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build image
          command: docker build -t osucass/spanish-english-demarcation:$CIRCLE_BRANCH .
      - run:
          name: Push image to Docker Hub
          command: docker push osucass/spanish-english-demarcation:$CIRCLE_BRANCH

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build
      - push_image:
          filters:
            branches:
              only:
                - dev
                - staging
                - master
          requires:
            - build
