version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run MSBuild
          command: dotnet build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  update_version:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: npm ci
      - run:
          name: Release new version
          command: npx semantic-release

  push_dev_image:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set TAG_VERSION and update PATH
          command: |
            echo 'export TAG_VERSION=$((git describe --tags $(git rev-list --tags --max-count=1)) | cut -c 2-)' >> $BASH_ENV'
            source $BASH_ENV
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build image
          command: docker build -t osucass/spanish-english-demarcation:dev-$TAG_VERSION .
      - run:
          name: Push image to Docker Hub
          command: docker push osucass/spanish-english-demarcation:dev-$TAG_VERSION

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build
      - update_version:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - dev
      - push_dev_image:
          requires:
            - update_version
          # filters:
          #   branches:
          #     only:
          #       - dev
          #       - master
