version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "SmarterBalanced.SpanishEnglishDemarcation/package.json" }}

      - run:
          name: install-npm-dependencies
          command: |
            cd SmarterBalanced.SpanishEnglishDemarcation
            npm install

      - save_cache:
          key: dependency-cache-{{ checksum "SmarterBalanced.SpanishEnglishDemarcation/package.json" }}
          paths:
            - ./SmarterBalanced.SpanishEnglishDemarcation/node_modules

      - run:
          name: build-dotnet-app
          command: |
            cd SmarterBalanced.SpanishEnglishDemarcation
            dotnet build